version: "3"

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:22.02-py3
    command: "tritonserver --exit-on-error=false --model-control-mode=explicit --load-model sid-minibert-onnx --model-repository=/models/triton-model-repo"
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
    ports:
      - "8000"
      - "8001"
      - "8002"
    runtime: nvidia
    volumes:
      - "${MORPHEUS_HOME:?Must set MORPHEUS_HOME to the Morpheus repo directory}/models:/models"

  gui:
    image: sid-viz:latest
    build:
      context: .
      # target: base
    cap_add:
      - SYS_PTRACE
    command: yarn start
    environment:
      DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
      DISPLAY: "${DISPLAY:-}"
      NVIDIA_DRIVER_CAPABILITIES: all
      TERM: "${TERM:-}" # Colorize the terminal in the container if possible
      MORPHEUS_SOCKET_URL: "morpheus:8765"
    stdin_open: true
    tty: true
    volumes:
      - ./:/opt/rapids/viz
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR:-/run/user/$UID}:${XDG_RUNTIME_DIR:-/run/user/$UID}
    # network_mode: host
    working_dir: /opt/rapids/viz
    runtime: nvidia
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined

  morpheus:
    image: morpheus:latest
    command: bash
    cap_add:
      - SYS_NICE
    depends_on:
      - gui
      - triton
    environment:
      - BUILD_DIR=build-docker
    ports:
      - "8765"
    stdin_open: true
    tty: true
    volumes:
      - "${MORPHEUS_HOME:?Must set MORPHEUS_HOME to the Morpheus repo directory}:/workspace"
